name: devices_lan
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  # 网络传输的必备包：nsd做服务发现和注册，websockt传递<10M的信息，network_info_plus获取本地的网络信息
  nsd: ^4.0.0
  web_socket_channel: ^3.0.0
  network_info_plus: ^6.0.0
  # 用于持久化重要数据到本地
  shared_preferences: ^2.5.3

  # 序列化+安全包
  protobuf: ^5.0.0
  fixnum: ^1.1.0
  encrypt: ^5.0.0

  # 文件选择和IO
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  mime: ^1.0.0

  # 随机昵称和头像缓存
  faker: ^2.1.0
  cached_network_image: ^3.3.1
  image: ^4.2.0

  # 状态管理
  riverpod: ^3.0.0
  hooks_riverpod: ^3.0.0
  freezed_annotation: ^2.4.1
  # flutter钩子函数（生命周期）
  flutter_hooks: ^0.21.3+1

  # 日志和uuid
  logger: ^2.3.0
  uuid: ^4.4.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod_annotation: ^3.0.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.12
  freezed: ^2.4.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
